In [57]:
import numpy as np

# คำสั่ง numpy

In [58]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
b = np.random.rand( 2, 3)
print(b)

[[0.33597972 0.61159641 0.44629945]
 [0.83791331 0.62077714 0.48273232]]


In [7]:
c = np.random.randn(3, 3)
print(c)

[[ 0.43341774 -1.8085519  -0.10488289]
 [-0.95314375 -0.50764643  1.42353543]
 [-0.67147552  0.6362797   1.81642171]]


In [18]:
d = np.random.randint(0, 100, size=3)
print(d)

[96 95 34]


In [24]:
e = np.linspace(1, 10, 5)
print(e)

[ 1.    3.25  5.5   7.75 10.  ]


In [26]:
print(np.min(e))
print(np.min(c))

1.0
-1.8085518969787284


In [28]:
print(np.argmin(e))
print(np.argmin(c))

0
1


In [29]:
print(np.argmax(e))
print(np.argmax(c))

4
8


In [37]:
f = np.arange(4, 10, 1)
print(f)

[4 5 6 7 8 9]


In [41]:
print(np.sqrt(f))

[2.         2.23606798 2.44948974 2.64575131 2.82842712 3.        ]


In [56]:
g = np.random.rand(4, 3)
print(g)
print('======')
g2 = np.delete(g, 1, 0)
print(g2)
print('======')
g2 = np.delete(g, 1, 1)
print(g2)

[[0.02266377 0.471438   0.10880198]
 [0.7019364  0.34036773 0.72811477]
 [0.26743997 0.57280517 0.92008672]
 [0.29745873 0.54773497 0.14139972]]
[[0.02266377 0.471438   0.10880198]
 [0.26743997 0.57280517 0.92008672]
 [0.29745873 0.54773497 0.14139972]]
[[0.02266377 0.10880198]
 [0.7019364  0.72811477]
 [0.26743997 0.92008672]
 [0.29745873 0.14139972]]


# คำสั่ง Matrix

In [61]:
h = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(h.T)

[[1 4]
 [2 5]
 [3 6]]


In [71]:
print( np.ones( (3, 2) ) )
print( np.zeros( (3, 2) ) )

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [77]:
a = np.zeros( (3, 1) )
b = np.ones( (3, 3) )
c = np.hstack((a, b))
print(c)

[[0. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 1. 1. 1.]]


In [118]:
a = np.array([
    [1, 2,  3],
    [4, 5, 6]
])
b = np.array([
    [2],
    [1],
    [1]
])
print(np.dot(a, b))

[[ 7]
 [19]]


In [123]:
print(np.shape(a))
print('======')
print(np.reshape(a,  (2, 3) ))
print('======')
print(np.reshape(a,  (3, 2) ))

(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [128]:
print(a.sum(axis = 0))
print(a.sum(axis = 1))
print(a.sum())

[5 7 9]
[ 6 15]
21


In [129]:
print(a.mean(axis = 0))
print(a.mean(axis = 1))
print(a.mean())

[2.5 3.5 4.5]
[2. 5.]
3.5


In [130]:
from numpy.linalg import inv

c = np.array([
    [1, 2],
    [3, 4]
])
print(c)
print('======')
d =  np.linalg.inv(c)
print(d)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
